/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newproject;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author sakshamchanouria
 */
public class Admin_Booking_History extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Booking_History
     */
    ArrayList<BillClass> al;
    ArrayList<BillDetailsClass> al2;
    myclient obj;
    mytablemodel tm;
    mytablemodel2 tm2;
    public Admin_Booking_History() {
        initComponents();
        obj = new myclient();
        tm = new mytablemodel();
        tm2 = new mytablemodel2();
        al = new ArrayList<>();
        al2 = new ArrayList<>();
        jTable1.setModel(tm);
        jTable2.setModel(tm2);
        
        al = obj.fetchBills();
        tm.fireTableDataChanged();
        
        
        Dimension d= new Dimension(Toolkit.getDefaultToolkit().getScreenSize());
        setSize(d.width,d.height);
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    class mytablemodel extends AbstractTableModel
    {

        @Override
        public int getRowCount() {
            return al.size();
        }

        @Override
        public int getColumnCount() {
            return 6;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            BillClass obj = al.get(rowIndex);

            if (columnIndex == 0) {
                return obj.BillId+"";
            } else if (columnIndex == 1) {
                return obj.PhoneNo;
            } else if(columnIndex==2){
                return obj.AdminGmail;
            }
             else if(columnIndex==3){
                return obj.Date_time;
            }
            else if(columnIndex==4){
                return obj.Payment_Type;
            }
            else if(columnIndex==5){
                return obj.Total+"";
            }
            
            else{
                return null;
            }
        }

        @Override
        public String getColumnName(int j) {
            String col[] = {"BillID", "PhoneNo", "Admin Gmail","Date-Time","Payment Mode","Total"};
            return col[j];
        }

    }
    
    class mytablemodel2 extends AbstractTableModel
    {

        @Override
        public int getRowCount() {
            return al2.size();
        }

        @Override
        public int getColumnCount() {
            return 5;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            BillDetailsClass obj = al2.get(rowIndex);

            if (columnIndex == 0) {
                return obj.BillDetailID+"";
            } else if (columnIndex == 1) {
                return obj.PName;
            } else if(columnIndex==2){
                return obj.PricePerUnit+"";
            }
             else if(columnIndex==3){
                return obj.Quantity;
            }
            else if(columnIndex==4){
                int price = Integer.parseInt(obj.PricePerUnit);
                int quantity = Integer.parseInt(obj.Quantity);
                return (price*quantity)+"";
            }
            
            else{
                return null;
            }
        }

        @Override
        public String getColumnName(int j) {
            String col[] = {"BillDetailsID", "Product", "Price Per Unit","Quantity","Total"};
            return col[j];
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(22, 180, 710, 402);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(782, 180, 580, 402);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setText("Booking History");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(540, 20, 410, 60);

        back.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(0, 51, 204));
        back.setText("Go Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(10, 20, 90, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        AdminHome obj = new AdminHome();
        dispose();
    }//GEN-LAST:event_backActionPerformed

    String bID="";
    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        
        if(row!=-1){
            Object value = jTable1.getValueAt(row, 0);
            bID = (String) value;
            System.out.println("Clicked : " + value);
            
            al2 = obj.getBillDetails(bID);
            System.out.println("I have got arraylost");
            tm2.fireTableDataChanged();
        }
    }//GEN-LAST:event_jTable1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Booking_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Booking_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Booking_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Booking_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Booking_History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
