/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newproject;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.InterfaceAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.util.Enumeration;
import javax.swing.ImageIcon;

/**
 *
 * @author sakshamchanouria
 */
public class ManageServer extends javax.swing.JFrame {

    /**
     * Creates new form ManageServer
     */
    public ManageServer() {
        
        
        
        initComponents();
        
        Dimension d= new Dimension(Toolkit.getDefaultToolkit().getScreenSize());
        
        // Background Image
        photoLB.setBounds(0,0,d.width,d.height);
        ImageIcon i1 = new ImageIcon("src/uploads/background.jpg");
        Image resized = i1.getImage().getScaledInstance(photoLB.getWidth(), photoLB.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i2 = new ImageIcon(resized);
        photoLB.setIcon(i2);
        
        setSize(691, 457);
        setLocationRelativeTo(null);
        setTitle("Server Side");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        bt3 = new javax.swing.JButton();
        photoLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        start.setBackground(new java.awt.Color(255, 186, 196));
        start.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        start.setForeground(new java.awt.Color(9, 21, 64));
        start.setText("START SERVER");
        start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start);
        start.setBounds(210, 70, 230, 80);

        stop.setBackground(new java.awt.Color(255, 186, 196));
        stop.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        stop.setForeground(new java.awt.Color(9, 21, 64));
        stop.setText("STOP SERVER");
        stop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        getContentPane().add(stop);
        stop.setBounds(210, 180, 230, 70);

        label1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(9, 21, 64));
        label1.setText("Server started at Port no. 8000");
        getContentPane().add(label1);
        label1.setBounds(10, 380, 210, 20);

        label2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(9, 21, 64));
        label2.setText("Use this IP address to connect : ");
        getContentPane().add(label2);
        label2.setBounds(10, 400, 360, 16);

        bt3.setBackground(new java.awt.Color(255, 186, 196));
        bt3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        bt3.setForeground(new java.awt.Color(9, 21, 64));
        bt3.setText("Admin Login");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt3);
        bt3.setBounds(210, 270, 230, 70);

        photoLB.setText("jLabel1");
        getContentPane().add(photoLB);
        photoLB.setBounds(20, 20, 42, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        try{
            String ip = "";
            MyServer obj = new MyServer(8000);
            try {

                    Enumeration<NetworkInterface> networkInterfaceEnumeration = NetworkInterface.getNetworkInterfaces();
                    while (networkInterfaceEnumeration.hasMoreElements()) {
                        for (InterfaceAddress interfaceAddress : networkInterfaceEnumeration.nextElement().getInterfaceAddresses()) {
                            if (interfaceAddress.getAddress().isSiteLocalAddress()) {
                                ip = interfaceAddress.getAddress().getHostAddress();
                            }
                        }
                    }
                } catch (SocketException e) {
                    e.printStackTrace();
                }
            
            System.out.println("Ip:"+ip);
        
        
            start.setEnabled(false);
            stop.setEnabled(true);

            label1.setText("Server started at Port no. 8000");
            label2.setText("Use this IP address to connect : " + ip);
            label2.setVisible(true);
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_startActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        // TODO add your handling code here:
        start.setEnabled(true);
        stop.setEnabled(false);
        
        label1.setText("Please Start the Server");
        label2.setVisible(false);
    }//GEN-LAST:event_stopActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        AdminLogin obj = new AdminLogin();
        dispose();
    }//GEN-LAST:event_bt3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt3;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel photoLB;
    private javax.swing.JButton start;
    private javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables
}
